policies:
- spec:
    body:
      required: false
    conventional:
      scopes:
      - apps
      - checks
      - common
      - darwin
      - flake
      - home-manager-modules
      - hydra
      - lib
      - linux
      - modules
      - options
      - overlays
      - packages
      - secrets
      - shells
      - static
      - tooling
      - users
      types:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - release
      - style
      - test
    gpg:
      required: true
    header:
      case: lower
      imperative: true
      invalidLastCharacters: .
      length: 80
  type: commit
